# Generated by Django 5.1.4 on 2025-06-05 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100, unique=True)),
                ('admin_shopname', models.CharField(max_length=150, unique=True)),
                ('admin_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('admin_phno', models.CharField(blank=True, max_length=15, null=True)),
                ('admin_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('admin_country', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_state', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_mundale', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_city_or_village', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('user_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('user_phno', models.CharField(blank=True, max_length=15, null=True)),
                ('user_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('user_country', models.CharField(blank=True, max_length=100, null=True)),
                ('user_state', models.CharField(blank=True, max_length=100, null=True)),
                ('user_mundale', models.CharField(blank=True, max_length=100, null=True)),
                ('user_city_or_village', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdapp.admin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdapp.user')),
            ],
        ),
    ]
