# Generated by Django 5.1.4 on 2025-06-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
