# Generated by Django 5.1.4 on 2025-06-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdapp', '0002_admin_admin_password_user_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.IntegerField(blank=True, unique=True)),
                ('user', models.IntegerField(blank=True, unique=True)),
                ('product', models.IntegerField(blank=True, unique=True)),
            ],
        ),
    ]
