# Generated by Django 5.1.4 on 2025-06-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdapp', '0003_cart1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart1',
        ),
        migrations.AddField(
            model_name='product',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tdapp.admin'),
        ),
    ]
