# Generated by Django 5.1.4 on 2025-06-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdapp', '0004_delete_cart1_product_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
