# Generated by Django 5.1.4 on 2025-06-08 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdapp', '0005_product_product_brand_product_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdapp.admin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdapp.user')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
