# Generated by Django 5.1.4 on 2025-06-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdapp', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
