# Generated by Django 5.1.4 on 2025-06-10 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdapp', '0007_product_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdapp.admin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdapp.user')),
            ],
        ),
    ]
